services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - jupyter-notebook-data:/home/jovyan/work
    networks:
      - learning-analytics-at-home
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'

volumes:
  jupyter-notebook-data:
    name: jupyter-notebook-data

networks:
  learning-analytics-at-home:
    name: learning-analytics-at-home
    driver: bridge
