version: '3'

services:
  superset:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin
      - DATABASE_DB=superset
      - DATABASE_HOST=superset-postgres
      - DATABASE_PASSWORD=superset
      - DATABASE_USER=superset
      - SUPERSET_SECRET_KEY=350303eb25fe0c874be356261c15642d1bf289635e6e4465
    ports:
      - '8088:8088'
    depends_on:
      - superset-postgres

  superset-postgres:
    image: postgres:15
    container_name: superset_postgres
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_USER=superset
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: superset-postgres
