services:
  learninglocker:
    image: ghcr.io/kromiii/learninglocker:latest
    container_name: learninglocker
    depends_on:
      - learninglocker-mongo
      - learninglocker-redis
    ports:
      - "3000:3000"
      - "8082:8080"
      - "8081:8081"
    volumes:
      - .env.learninglocker:/usr/local/src/learninglocker/.env
      - .env.xapi-service:/usr/local/src/xapi-service/.env
    networks:
      - learning-analytics-at-home
    working_dir: /usr/local/src/learninglocker
    command: bash -c "source ~/.bashrc && yarn migrate && pm2 start pm2/all.json && cd ../xapi-service && pm2 start pm2/xapi.json && pm2 logs"

  learninglocker-mongo:
    image: mongo:4.0.8
    container_name: learninglocker-mongo
    restart: always
    volumes:
      - learninglocker-mongo:/data/db
    networks:
      - learning-analytics-at-home

  learninglocker-redis:
    image: redis:5.0.4
    container_name: learninglocker-redis
    restart: always
    volumes:
      - learninglocker-redis:/data
    networks:
      - learning-analytics-at-home
    command: redis-server --appendonly yes

volumes:
  learninglocker-mongo:
    name: learninglocker-mongo
  learninglocker-redis:
    name: learninglocker-redis

networks:
  learning-analytics-at-home:
    name: learning-analytics-at-home
    driver: bridge
